# Generated by Django 4.2 on 2023-06-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short_code', models.SlugField(unique=True)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
