# Generated by Django 4.2 on 2023-06-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_shortener_delete_urlmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
